// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvscYJczxv0CqSjKUxo_VN3KnX8tn0mMs',
    appId: '1:122734005829:web:bd5025f19c2d74cef29d2c',
    messagingSenderId: '122734005829',
    projectId: 'e-commerce-d3fec',
    authDomain: 'e-commerce-d3fec.firebaseapp.com',
    storageBucket: 'e-commerce-d3fec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnmPEBLVXr210YYUYuK3lEAeZWUncJI-g',
    appId: '1:122734005829:android:efa087ebe8510208f29d2c',
    messagingSenderId: '122734005829',
    projectId: 'e-commerce-d3fec',
    storageBucket: 'e-commerce-d3fec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0d5sxmZ-AVrJhYYmoPQb15dgufVzkL2Q',
    appId: '1:122734005829:ios:3971f5364a53c4fff29d2c',
    messagingSenderId: '122734005829',
    projectId: 'e-commerce-d3fec',
    storageBucket: 'e-commerce-d3fec.appspot.com',
    androidClientId: '122734005829-1fm9gr7np6i72fam7amrjmsqmi9v1b8g.apps.googleusercontent.com',
    iosClientId: '122734005829-hhlkmusjcdmd7l13v6n8eft6r14actbl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0d5sxmZ-AVrJhYYmoPQb15dgufVzkL2Q',
    appId: '1:122734005829:ios:0ffa55ccb2edbcc9f29d2c',
    messagingSenderId: '122734005829',
    projectId: 'e-commerce-d3fec',
    storageBucket: 'e-commerce-d3fec.appspot.com',
    androidClientId: '122734005829-1fm9gr7np6i72fam7amrjmsqmi9v1b8g.apps.googleusercontent.com',
    iosClientId: '122734005829-abh34amrogvf00mv02hj0k1r2h2vfm4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
