name: Confirm All Checks

on: 
    push:
        branches:
            - master

jobs:
    build:
        name: Build CLOT APP
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            
            - name: Install dependencies
              run: npm install