name: Confirm All Checks

on: 
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build CLOT APP
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'
            
            - name: Install dependencies
              run: npm install
            
            - name: Npm Build
              run: npm run build